name = "FinancialMarketSimulation"
uuid = "873f78ff-6396-4785-a014-dd5df8284ed2"
version = "1.0.0-DEV"
authors = ["Sliem el Ela"]

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
ComponentArrays = "0.15.32"
LinearAlgebra = "1.12.0"
Random = "1.11.0"
Statistics = "1.11.1"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
